# Base16 Tokyodark 256 - alacritty color config
# Tiagovla (https://github.com/tiagovla/)

# Default colors
[colors.primary]
background = '0x11121d'
foreground = '0xabb2bf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x11121d'
cursor = '0xabb2bf'

# Normal colors
[colors.normal]
black = '0x11121d'
red = '0xa485dd'
green = '0xd7a65f'
yellow = '0x7199ee'
blue = '0x95c561'
magenta = '0xee6d85'
cyan = '0xa485dd'
white = '0xabb2bf'

# Bright colors
[colors.bright]
black = '0x393a45'
red = '0xa485dd'
green = '0xd7a65f'
yellow = '0x7199ee'
blue = '0x95c561'
magenta = '0xee6d85'
cyan = '0xa485dd'
white = '0x2c2d38'

[[colors.indexed_colors]]
index = 16
color = "0xa485dd"

[[colors.indexed_colors]]
index = 17
color = "0x773440"

[[colors.indexed_colors]]
index = 18
color = "0x151621"

[[colors.indexed_colors]]
index = 19
color = "0x43444f"

[[colors.indexed_colors]]
index = 20
color = "0x1b1c27"

[[colors.indexed_colors]]
index = 21
color = "0x555661"
