# Base16 Everforest 256 - alacritty color config
# Sainnhe Park (https://github.com/sainnhe)

# Default colors
[colors.primary]
background = '0x2f383e'
foreground = '0xd3c6aa'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2f383e'
cursor = '0xd3c6aa'

# Normal colors
[colors.normal]
black = '0x2f383e'
red = '0x7fbbb3'
green = '0x83c092'
yellow = '0xdbbc7f'
blue = '0xa7c080'
magenta = '0xe67e80'
cyan = '0xe69875'
white = '0xd3c6aa'

# Bright colors
[colors.bright]
black = '0x859289'
red = '0x7fbbb3'
green = '0x83c092'
yellow = '0xdbbc7f'
blue = '0xa7c080'
magenta = '0xe67e80'
cyan = '0xe69875'
white = '0xfdf6e3'

[[colors.indexed_colors]]
index = 16
color = "0xd699b6"

[[colors.indexed_colors]]
index = 17
color = "0xeaedc8"

[[colors.indexed_colors]]
index = 18
color = "0x374247"

[[colors.indexed_colors]]
index = 19
color = "0x4a555b"

[[colors.indexed_colors]]
index = 20
color = "0x9da9a0"

[[colors.indexed_colors]]
index = 21
color = "0xe4e1cd"
